name: iron_dome_game
description: Iron Dome missile defense game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  flame_audio: ^2.1.1
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/city_skyline.png
    - assets/images/antenna.png
    - assets/images/shield.png
    - assets/images/iranian_missile.webp
    - assets/images/iron_dome_launcher.png
    - assets/images/crosshair.webp
    - assets/images/doors.png
    - assets/images/uav.png
    - assets/images/warhead_missile.jpg
    - assets/images/clouds.jpg
    - assets/audio/
